code/routes/web.php
        Route::get('/', 'UserAuthController@signup')->name('user.signup_get');
        Route::post('/', 'UserAuthController@handle_signup')->name('user.signup_post');
    });
    Route::group(['prefix' => 'signin'], function () {
        Route::get('/', 'UserAuthController@signin')->name('user.signin_get');
        Route::post('/', 'UserAuthController@handle_signin')->name('user.signin_post');
        Route::get('google', 'SocialLoginController@redirect_to_google')->name('social.google');
        Route::get('zalo', 'SocialLoginController@redirect_to_zalo')->name('social.zalo');
        Route::get('facebook', 'SocialLoginController@redirect_to_facebook')->name('social.facebook');
        Route::get('zalo-social', 'SocialLoginController@handle_signin_zalo');
        Route::get('google-social', 'SocialLoginController@handle_signin_google');
        Route::get('facebook-social', 'SocialLoginController@handle_signin_facebook');
    });
    Route::get('forgot-password', 'UserController@forgot_password')->name('user.forgot_password');
    Route::get('new-password/{code}', 'UserController@new_password')->name('user.new_password');
    Route::post('set-password', 'UserController@set_password')->name('user.set_password');
    Route::post('send-mail-password', 'MailController@handle_mail_reset_password')->name('mail.reset_password');


    Route::group(['prefix' => 'notification'], function () {
        Route::post('save-token', 'NotificationController@save_token');
    });

    Route::group(['middleware' => ['auth_user']], function () {
        Route::group(['prefix' => 'user'], function () {
            Route::get('/', 'UserController@index')->name('user.index');
            Route::post('update', 'UserController@update')->name('user.update');
        });
        Route::get('signout', 'UserAuthController@signout')->name('user.signout');
        Route::group(['prefix' => 'comment'], function () {
            Route::post('update', 'CommentController@update')->name('comment.update');
            Route::post('store', 'CommentController@store')->name('comment.store');
            Route::post('delete', 'CommentController@delete')->name('comment.delete');
        });
        Route::group(['prefix' => 'cart'], function () {
            Route::post('delete', 'CartController@delete')->name('cart.delete');
            Route::post('update', 'CartController@update')->name('cart.update');
            Route::post('store', 'CartController@store')->name('cart.store');
        });
        Route::group(['prefix' => 'checkout'], function () {
            Route::get('/', 'CheckoutController@index')->name('checkout.index');
            Route::post('calc-feeship', 'CheckoutController@calc_feeship')->name('checkout.calc_feeship');
        });
        Route::group(['prefix' => 'order'], function () {
            Route::get('/', 'OrderController@index')->name('order.index');
            Route::get('detail/{id}', 'OrderController@show')->name('order.show');
            Route::get('delete/{id}', 'OrderController@delete')->name('order.delete');

            Route::get('payment_callback', 'OrderController@payment_callback')->name('payment.callback');
            Route::post('order-confirm', 'OrderController@confirm_order')->name('order.confirm');
            Route::get('print-order/{id}', 'OrderController@print_order')->name('order.print');
        });
        Route::post('use-coupon', 'CouponController@use_coupon')->name('coupon.use_coupon');
        Route::post('select-delivery', 'DeliveryController@select_delivery');
        Route::group(['prefix' => 'chat'], function () {
            Route::post('get', 'ChatController@get_user_chat');
            Route::post('send', 'ChatController@send_user_chat');
        });
    });
});

//print
Route::group(['prefix' => 'print'], function () {
    Route::get('order/{code}', 'OrderController@print_order_new'); //middleware admin
});

//admin route
Route::get('admin/signin', 'AdminAuthController@signin')->name('admin.signin');
Route::post('admin/signin', 'AdminAuthController@handle_signin')->name('admin.handle_signin');
Route::group(['prefix' => 'admin',  'middleware' => ['auth:admin', 'auth_admin']], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('signout', 'AdminAuthController@signout')->name('admin.signout');
    Route::post('send-coupon', 'MailController@send_coupon');
    Route::group(['middleware' => 'can:' . config('role.ROLE')], function () {
        Route::resource('role', 'RoleController');
    });
    Route::group(['middleware' => 'can:' . config('role.POST')], function () {
        Route::resource('post', 'PostController');
    });
    Route::group(['middleware' => 'can:' . config('role.STATISTIC')], function () {
        Route::get('static', 'StaticController@index')->name('static.index');
    });
    Route::group(['middleware' => 'can:' . config('role.SLIDER')], function () {
        Route::resource('slider', 'SliderController');
    });
    Route::group(['middleware' => 'can:' . config('role.INFO')], function () {
        Route::get('device', 'DeviceController@admin_device')->name('device.admin');
        Route::resource('visitor', 'VisitorController');
    });
    Route::group(['middleware' => 'can:' . config('role.ADMIN')], function () {
        Route::get('list', 'AdminController@list')->name('admin.list');
        Route::get('add', 'AdminController@add')->name('admin.add');
        Route::get('edit/{id}', 'AdminController@edit')->name('admin.edit');
        Route::post('update/{id}', 'AdminController@update')->name('admin.update');
        Route::post('store', 'AdminController@store')->name('admin.store');
        Route::get('delete/{id}', 'AdminController@destroy')->name('admin.delete');
    });
    Route::group(['middleware' => 'can:' . config('role.BRAND')], function () {
        Route::post('brand/sort', 'BrandController@sort');
        Route::resource('brand', 'BrandController');
    });
    Route::group(['middleware' => 'can:' . config('role.COUPON')], function () {
        Route::post('coupon/send', 'CouponController@send');
        Route::resource('coupon', 'CouponController');
    });
    Route::group(['middleware' => 'can:' . config('role.COMMENT')], function () {
        Route::group(['prefix' => 'comment'], function () {
            Route::get('/', 'CommentController@index')->name('comment.index');
            Route::get('not-confirm', 'CommentController@get_not_confirm')->name('comment.not_confirm');
            Route::get('confirm/{id}', 'CommentController@set_confirm')->name('comment.confirm');
            Route::post('delete', 'CommentController@delete')->name('comment.delete');
        });
    });
    Route::group(['middleware' => 'can:' . config('role.ORDER')], function () {
        Route::group(['prefix' => 'order'], function () {
            Route::get('/', 'OrderController@manage')->name('order.manage');
            Route::get('/{id}', 'OrderController@admin_detail')->name('order.admin_detail');
            Route::get('print-order/{id}', 'OrderController@print_order')->name('order.admin_print');
            Route::get('order-delete/{id}', 'OrderController@admin_delete')->name('order.admin_delete');
            Route::get('order-delivery/{id}', 'OrderController@delivery')->name('order.delivery');
        });
    });
    Route::group(['middleware' => 'can:' . config('role.FEESHIP')], function () {
        Route::group(['prefix' => 'delivery'], function () {
            Route::post('select', 'DeliveryController@select_delivery')->name('delivery.select');
            Route::get('/', 'DeliveryController@index')->name('delivery.index');
            Route::post('store', 'DeliveryController@store')->name('delivery.store');
            Route::post('show', 'DeliveryController@show')->name('delivery.show');
            Route::post('delete', 'DeliveryController@delete')->name('delivery.delete');
        });
    });
    Route::group(['middleware' => 'can:' . config('role.PRODUCT')], function () {
        Route::group(['prefix' => 'product'], function () {
            Route::get('reference', 'ProductController@reference')->name('product.reference');
            Route::get('gallery/{id}', 'ProductController@product_gallery')->name('product.gallery');
            Route::get('delete-gallery/{id}', 'ProductController@delete_gallery')->name('product.gallery.delete');
            Route::post('gallery-store/{id}', 'ProductController@product_gallery_store')->name('product.gallery.store');
            Route::post('get-product-crawl', 'ProductController@get_product_crawl')->name('product.get_product_crawl');
            Route::post('add-product-crawl', 'ProductController@add_product_crawl')->name('product.add_product_crawl');
        });
        Route::resource('product', 'ProductController');
    });
    Route::group(['middleware' => 'can:' . config('role.USER')], function () {
        Route::group(['prefix' => 'user'], function () {
            Route::get('/', 'UserController@all_user')->name('user.list');
            Route::get('more/{id}', 'UserController@more_feature')->name('user.more');
            Route::post('unblock', 'UserController@unblock')->name('user.unblock');
            Route::post('block', 'UserController@block')->name('user.block');
            Route::post('delete', 'UserController@delete')->name('user.delete');
            Route::match(['get', 'post'], 'online', 'UserController@online_user')->name('user.online');
        });
        Route::get('device/{id}', 'DeviceController@user_device')->name('device.user');
        Route::group(['prefix' => 'chat'], function () {
            Route::post('get', 'ChatController@get_admin_chat');
            Route::post('send', 'ChatController@send_admin_chat');
        });
    });

    Route::group(['prefix' => 'notification'], function () {
        Route::get('add', 'NotificationController@add')->name('noti.add');

code/app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $fillable = [
        'name',
        'product_id',
        'show_hide',
        'image',
    ];

    public function product()
    {
        return $this->belongsTo('App\Models\Product', 'product_id');
    }
}

code/app/Http/Controllers/Api/SliderController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\SliderService;
use Exception;

class SliderController extends Controller
{
    protected $sliderService;

    public function __construct(SliderService $sliderService)
    {
        $this->sliderService = $sliderService;
    }

    public function get_slider()
    {
        $sliders = $this->sliderService->getLimit();
        return $this->successResponse($sliders);
    }

    public function all_slider()
    {
        $sliders = $this->sliderService->getAll();
        return $this->successResponse($sliders);
    }

    public function new_slider(Request $req)
    {
        try {
            $this->sliderService->save($req);
            return $this->successResponse();
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }

    public function update_slider(Request $req)
    {
        try {
            $this->sliderService->update($req);
            return $this->successResponse();
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }

    public function delete_slider(Request $req)
    {
        try {
            $this->sliderService->delete($req);
            return $this->successResponse();
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }
}

code/app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SliderRequest;
use App\Models\Product;
use App\Models\Slider;

class SliderController extends Controller
{
    public function index()
    {
        $sliders = Slider::all();
        return view('admin.slider.list')->with(compact(['sliders']));
    }

    public function create()
    {
        $products = Product::all();
        return view('admin.slider.add')->with(compact(['products']));
    }

    public function store(SliderRequest $req)
    {
        $slider = new Slider;
        $slider->fill($req->all());
        $slider->save();
        return redirect()->route('slider.index');
    }

    public function edit(Slider $slider)
    {
        $products = Product::all();
        return view('admin.slider.edit')->with(compact(['products', 'slider']));
    }

    public function update(SliderRequest $req, $id)
    {
        $slider = Slider::find($id);
        if ($req->hasFile('image')) {
            deleteImage($slider->image, 'sliders');
        }
        $slider->fill($req->all());
        $slider->save();
        return redirect()->route('slider.index');
    }

    public function destroy($id)
    {
        Slider::find($id)->delete();
        return redirect()->route('slider.index');
    }
}

code/resources/views/admin/slider/add.blade.php
@extends('admin.layouts.master')
@section('title', 'Thêm Slider')
@section('title_page', 'Thêm Slider')
@section('sub_title_page', 'Thêm Slider cho sản phẩm')

@section('content_page')
<script>
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            var forms = document.getElementsByClassName('needs-validation');
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>

<div class="card-body">
    <h5 class="card-title">Thêm Slider</h5>
    <form class="needs-validation" action="{{route('slider.store')}}" method="POST" enctype="multipart/form-data" novalidate>
        @csrf
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Tên slider</label>
                <input type="text" class="form-control" name="name" id="validationTooltip01" placeholder="Tên slider" value="" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-4 mb-3">
                <label for="">Sản phẩm</label>
                <select class="mb-2 form-control" name="product_id">
                    @foreach($products as $product)
                    <option value="{{$product->id}}">{{$product->name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Ẩn/Hiện</label>
                <select class="mb-2 form-control" name="show_hide">
                    <option value="1" selected>Hiện</option>
                    <option value="0">Ẩn</option>
                </select>
            </div>
        </div>

        <div class="form-row">
            <div class="col-md-12 mb-12">
                <div class="custom-file">
                    <label for="validationTooltip01">Hình ảnh</label>
                    <input type="file" class="form-control" name="image" id="validatedCustomFile" accept=".PNG, .JPEG, .JPG" required>
                    <div class="invalid-feedback">Vui lòng chọn một trong các định dạng ảnh: PNG, JPG, JPEG.</div>
                    <div class="valid-feedback">Tuyệt vời!!!</div>
                </div>
            </div>
        </div>

        <div class="form-row text-center">
            <div class="col-md-12 mb-3 mt-2">
                <button class="btn btn-success " name="submit" style="padding-left: 35px; padding-right:35px ;" type="submit">Thêm</button>
            </div>
        </div>

    </form>
</div>

@endsection

code/resources/views/admin/slider/edit.blade.php
@extends('admin.layouts.master')
@section('title', 'Chỉnh sửa Slider')
@section('title_page', 'Chỉnh sửa Slider')
@section('sub_title_page', 'Chỉnh sửa Slider cho sản phẩm')

@section('content_page')
<script>
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            var forms = document.getElementsByClassName('needs-validation');
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>

<div class="card-body">
    <h5 class="card-title">Chỉnh sửa Slider</h5>
    <form class="needs-validation" action="{{route('slider.update', $slider->id)}}" method="POST" enctype="multipart/form-data" novalidate>
        @csrf
        @method('PUT')
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Tên slider</label>
                <input type="text" class="form-control" name="name" id="validationTooltip01" placeholder="Tên slider" value="{{$slider->name}}" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-4 mb-3">
                <label for="">Sản phẩm</label>
                <select class="mb-2 form-control" name="product_id">
                    @foreach($products as $product)
                    <option @if($slider->product_id == $product->id) selected @endif value="{{$product->id}}">{{$product->name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Ẩn/Hiện</label>
                <select class="mb-2 form-control" name="show_hide">
                    @if($slider->show_hide == 1)
                    <option selected value="1">Hiển thị</option>
                    <option value="0">Ẩn</option>
                    @else
                    <option value="1">Hiển thị</option>
                    <option selected value="0">Ẩn</option>
                    @endif
                </select>
            </div>

            <div class="col-md-12 mb-3">
                <div class="custom-file">
                    <label for="validationTooltip01">Hình ảnh</label>
                    <input type="file" class="form-control" name="image" id="validatedCustomFile" accept=".PNG, .JPEG, .JPG">
                    <div class="invalid-feedback">Vui lòng chọn một trong các định dạng ảnh: PNG, JPG, JPEG.</div>
                    <div class="valid-feedback">Tuyệt vời!!!</div>
                    @if ($errors->has('file_error'))
                    <div class="">{{ $errors->first('file_error')}}</div>
                    @endif
                </div>
            </div>
        </div>

        <div class="form-row text-center">
            <div class="col-12">
                <p class="text-noti">Logo sản phẩm hiện tại</p>
                <img class="rounded-circle border-circle" src="{{asset('admins/uploads/sliders/'.$slider->image)}}" alt="">
            </div>
        </div>

        <div class="form-row text-center">
            <div class="col-md-12 mb-3 mt-2">
                <button class="btn btn-success " name="submit" style="padding-left: 35px; padding-right:35px ;" type="submit">Cập nhật</button>
            </div>
        </div>

    </form>
</div>

@endsection

code/resources/views/admin/slider/list.blade.php
@extends('admin.layouts.master')
@section('title', 'Danh sách slider')
@section('title_page', 'Danh sách slider')
@section('sub_title_page', 'Danh sách slider')

@section('content_page')
<div class="card-header">Danh sách slider</div>
<div class="table-responsive" style="padding-bottom: 10px;">
    @if(count($sliders) > 0)
    <table class="align-middle mb-0 table table-borderless table-striped table-hover">
        <thead>
            <tr>
                <th class="text-center">STT</th>
                <th>Tên slider</th>
                <th class="text-center">Hiện/ Ẩn</th>
                <th class="text-center">Tính năng</th>
            </tr>
        </thead>
        <tbody>
            <?php $i = 1; ?>
            @foreach ($sliders as $slider)
            <tr>
                <td class="text-center text-muted">
                    <?php
                    echo $i;
                    $i++;
                    ?></td>
                <td>
                    <div class="widget-content p-0">
                        <div class="widget-content-wrapper">
                            <div class="widget-content-left mr-3">
                                <div class="widget-content-left">
                                    <img class="border-circle" src="{{asset('admins/uploads/sliders/'.$slider->image)}}" alt="">
                                </div>
                            </div>
                            <div class="widget-content-left flex2">
                                <div class="widget-heading">{{$slider->name}}</div>
                                <div class="widget-subheading opacity-7"></div>
                            </div>
                        </div>
                    </div>
                </td>

                <td class="text-center text-muted">
                    @if($slider->show_hide == 1)
                    Hiển thị
                    @else
                    Ẩn
                    @endif
                </td>

                <td class="text-center">
                    <a href="{{route('slider.edit', $slider->id)}}" class="btn btn-primary btn-sm">Chỉnh sửa</a>
                    <form action="{{route('slider.destroy', $slider->id)}}" class="form-delete" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger btn-sm">Xóa</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <div class="text-center text-noti">Không có slider nào để hiển thị</div>
    @endif
</div>
@endsection