code/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('lang/{locale}', function ($locale) {
    if (!in_array($locale, ['en', 'vi'])) abort(400);
    session(['locale' => $locale]);
    return redirect()->back();
})->name('lang');

Route::group(['middleware' => ['auth:sanctum']], function () {
    Route::get('order/print/{id}', 'OrderController@print_order')->name('order.print');
});

Route::get('blocked', 'UserController@blocked')->name('user.blocked');
Route::group(['middleware' => ['block_user', 'visitor', 'user_online']], function () {
    Route::get('/', 'HomeController@index')->name('home.index');
    Route::resource('contact', 'ContactController');
    Route::get('rss', 'NewsController@rssNew')->name('news.rss');
    Route::resource('news', 'NewsController');
    Route::resource('music', 'MusicController');
    Route::resource('covid', 'CovidController');
    Route::resource('weather', 'WeatherController');
    Route::any('search', 'SearchController@search')->name('search');
    Route::post('search-live', 'SearchController@search_live')->name('search.live');
    Route::get('product/{id}', 'ProductController@detail')->name('product.detail');
    Route::get('cart', 'CartController@index')->name('cart.index');
    Route::group(['prefix' => 'signup'], function () {
        Route::get('/', 'UserAuthController@signup')->name('user.signup_get');
        Route::post('/', 'UserAuthController@handle_signup')->name('user.signup_post');
    });
    Route::group(['prefix' => 'signin'], function () {
        Route::get('/', 'UserAuthController@signin')->name('user.signin_get');
        Route::post('/', 'UserAuthController@handle_signin')->name('user.signin_post');
        Route::get('google', 'SocialLoginController@redirect_to_google')->name('social.google');
        Route::get('zalo', 'SocialLoginController@redirect_to_zalo')->name('social.zalo');
        Route::get('facebook', 'SocialLoginController@redirect_to_facebook')->name('social.facebook');
        Route::get('zalo-social', 'SocialLoginController@handle_signin_zalo');
        Route::get('google-social', 'SocialLoginController@handle_signin_google');
        Route::get('facebook-social', 'SocialLoginController@handle_signin_facebook');
    });
    Route::get('forgot-password', 'UserController@forgot_password')->name('user.forgot_password');
    Route::get('new-password/{code}', 'UserController@new_password')->name('user.new_password');
    Route::post('set-password', 'UserController@set_password')->name('user.set_password');
    Route::post('send-mail-password', 'MailController@handle_mail_reset_password')->name('mail.reset_password');


    Route::group(['prefix' => 'notification'], function () {
        Route::post('save-token', 'NotificationController@save_token');
    });

    Route::group(['middleware' => ['auth_user']], function () {
        Route::group(['prefix' => 'user'], function () {
            Route::get('/', 'UserController@index')->name('user.index');
            Route::post('update', 'UserController@update')->name('user.update');
        });
        Route::get('signout', 'UserAuthController@signout')->name('user.signout');
        Route::group(['prefix' => 'comment'], function () {
            Route::post('update', 'CommentController@update')->name('comment.update');
            Route::post('store', 'CommentController@store')->name('comment.store');
            Route::post('delete', 'CommentController@delete')->name('comment.delete');
        });
        Route::group(['prefix' => 'cart'], function () {
            Route::post('delete', 'CartController@delete')->name('cart.delete');
            Route::post('update', 'CartController@update')->name('cart.update');
            Route::post('store', 'CartController@store')->name('cart.store');
        });
        Route::group(['prefix' => 'checkout'], function () {
            Route::get('/', 'CheckoutController@index')->name('checkout.index');
            Route::post('calc-feeship', 'CheckoutController@calc_feeship')->name('checkout.calc_feeship');
        });
        Route::group(['prefix' => 'order'], function () {
            Route::get('/', 'OrderController@index')->name('order.index');
            Route::get('detail/{id}', 'OrderController@show')->name('order.show');
            Route::get('delete/{id}', 'OrderController@delete')->name('order.delete');

            Route::get('payment_callback', 'OrderController@payment_callback')->name('payment.callback');
            Route::post('order-confirm', 'OrderController@confirm_order')->name('order.confirm');
            Route::get('print-order/{id}', 'OrderController@print_order')->name('order.print');
        });
        Route::post('use-coupon', 'CouponController@use_coupon')->name('coupon.use_coupon');
        Route::post('select-delivery', 'DeliveryController@select_delivery');
        Route::group(['prefix' => 'chat'], function () {
            Route::post('get', 'ChatController@get_user_chat');
            Route::post('send', 'ChatController@send_user_chat');
        });
    });
});

//print
Route::group(['prefix' => 'print'], function () {
    Route::get('order/{code}', 'OrderController@print_order_new'); //middleware admin
});

//admin route
Route::get('admin/signin', 'AdminAuthController@signin')->name('admin.signin');
Route::post('admin/signin', 'AdminAuthController@handle_signin')->name('admin.handle_signin');
Route::group(['prefix' => 'admin',  'middleware' => ['auth:admin', 'auth_admin']], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('signout', 'AdminAuthController@signout')->name('admin.signout');
    Route::post('send-coupon', 'MailController@send_coupon');
    Route::group(['middleware' => 'can:' . config('role.ROLE')], function () {
        Route::resource('role', 'RoleController');
    });
    Route::group(['middleware' => 'can:' . config('role.POST')], function () {
        Route::resource('post', 'PostController');
    });
    Route::group(['middleware' => 'can:' . config('role.STATISTIC')], function () {
        Route::get('static', 'StaticController@index')->name('static.index');
    });
    Route::group(['middleware' => 'can:' . config('role.SLIDER')], function () {
        Route::resource('slider', 'SliderController');
    });
    Route::group(['middleware' => 'can:' . config('role.INFO')], function () {
        Route::get('device', 'DeviceController@admin_device')->name('device.admin');
        Route::resource('visitor', 'VisitorController');
    });
    Route::group(['middleware' => 'can:' . config('role.ADMIN')], function () {
        Route::get('list', 'AdminController@list')->name('admin.list');
        Route::get('add', 'AdminController@add')->name('admin.add');
        Route::get('edit/{id}', 'AdminController@edit')->name('admin.edit');
        Route::post('update/{id}', 'AdminController@update')->name('admin.update');
        Route::post('store', 'AdminController@store')->name('admin.store');
        Route::get('delete/{id}', 'AdminController@destroy')->name('admin.delete');
    });
    Route::group(['middleware' => 'can:' . config('role.BRAND')], function () {
        Route::post('brand/sort', 'BrandController@sort');
        Route::resource('brand', 'BrandController');
    });
    Route::group(['middleware' => 'can:' . config('role.COUPON')], function () {
        Route::post('coupon/send', 'CouponController@send');
        Route::resource('coupon', 'CouponController');
    });
    Route::group(['middleware' => 'can:' . config('role.COMMENT')], function () {
        Route::group(['prefix' => 'comment'], function () {
            Route::get('/', 'CommentController@index')->name('comment.index');
            Route::get('not-confirm', 'CommentController@get_not_confirm')->name('comment.not_confirm');
            Route::get('confirm/{id}', 'CommentController@set_confirm')->name('comment.confirm');
            Route::post('delete', 'CommentController@delete')->name('comment.delete');
        });
    });
    Route::group(['middleware' => 'can:' . config('role.ORDER')], function () {
        Route::group(['prefix' => 'order'], function () {
            Route::get('/', 'OrderController@manage')->name('order.manage');
            Route::get('/{id}', 'OrderController@admin_detail')->name('order.admin_detail');
            Route::get('print-order/{id}', 'OrderController@print_order')->name('order.admin_print');
            Route::get('order-delete/{id}', 'OrderController@admin_delete')->name('order.admin_delete');
            Route::get('order-delivery/{id}', 'OrderController@delivery')->name('order.delivery');
        });
    });
    Route::group(['middleware' => 'can:' . config('role.FEESHIP')], function () {
        Route::group(['prefix' => 'delivery'], function () {
            Route::post('select', 'DeliveryController@select_delivery')->name('delivery.select');
            Route::get('/', 'DeliveryController@index')->name('delivery.index');
            Route::post('store', 'DeliveryController@store')->name('delivery.store');
            Route::post('show', 'DeliveryController@show')->name('delivery.show');
            Route::post('delete', 'DeliveryController@delete')->name('delivery.delete');
        });
    });
    Route::group(['middleware' => 'can:' . config('role.PRODUCT')], function () {
        Route::group(['prefix' => 'product'], function () {
            Route::get('reference', 'ProductController@reference')->name('product.reference');
            Route::get('gallery/{id}', 'ProductController@product_gallery')->name('product.gallery');

code/app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\PostService;
use Exception;

class PostController extends Controller
{
    protected $postService;

    public function __construct(PostService $postService)
    {
        $this->postService = $postService;
    }

    public function all_post()
    {
        $posts = $this->postService->getAll();
        return $this->successResponse($posts);
    }

    public function get_post(Request $req)
    {
        $post = $this->postService->getById($req);
        return $this->successResponse($post);
    }

    public function update_post(Request $req)
    {
        try {
            $this->postService->updateOrSave($req);
            return $this->successResponse();
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }

    public function delete_post(Request $req)
    {
        try {
            $this->postService->delete($req);
            return $this->successResponse();
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }
}

code/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostRequest;
use App\Models\PostProduct;
use App\Models\Product;

class PostController extends Controller
{
    public function index()
    {
        $posts = PostProduct::all();
        return view('admin.post.list')->with(compact(['posts']));
    }

    public function create()
    {
        $products = Product::all();
        return view('admin.post.add')->with(compact(['products']));
    }

    public function store(PostRequest $req)
    {
        $post = new PostProduct;
        $post->fill($req->all());
        $post->save();
        return redirect()->route('post.index');
    }

    public function edit(PostProduct $post)
    {
        return view('admin.post.edit')->with(compact(['post']));
    }

    public function update(PostRequest $req, $id)
    {
        $post = PostProduct::find($id);
        $post->fill($req->all());
        $post->save();
        return redirect()->route('post.index');
    }

    public function destroy($id)
    {
        PostProduct::destroy($id);
        return \redirect()->route('post.index');
    }
}

code/resources/views/admin/post/add.blade.php
@extends('admin.layouts.master')
@section('title', 'Thêm bài viết')
@section('title_page', 'Thêm bài viết')
@section('sub_title_page', 'Thêm bài viết cho sản phẩm')

@section('content_page')
<script>
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            var forms = document.getElementsByClassName('needs-validation');
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>

<div class="card-body">
    <h5 class="card-title">Thêm bài viết</h5>
    <form class="needs-validation" action="{{route('post.store')}}" method="POST" enctype="multipart/form-data" novalidate>
        @csrf
        <div class="form-row">
            <div class="col-md-6 mb-3">
                <label for="validationTooltip01">Sản phẩm</label>
                <select class="mb-2 form-control" name="product_id">
                    @foreach($products as $product)
                    @if(!$product->post)
                    <option value="{{$product->id}}">{{$product->name}}</option>
                    @endif
                    @endforeach
                </select>
            </div>

            <div class="col-md-12 mb-3">
                <label for="validationTooltip01">Mô tả bài viết</label>
                <textarea style="resize: none" rows="3" class="form-control" name="title" id="ckeditor1" placeholder="Mô tả cho bài viết"></textarea>
            </div>

            <div class="col-md-12 mb-3">
                <label for="validationTooltip01">Nôi dung bài viết</label>
                <textarea style="resize: none" rows="10" class="form-control" name="content" id="ckeditor2" placeholder="Nội dung cho bài viết"></textarea>
            </div>

        </div>

        <div class="form-row text-center">
            <div class="col-md-12 mb-3 mt-2">
                <button class="btn btn-success " name="submit" style="padding-left: 35px; padding-right:35px ;" type="submit">Thêm</button>
            </div>
        </div>

    </form>
</div>
@endsection

code/resources/views/admin/post/edit.blade.php
@extends('admin.layouts.master')
@section('title', 'Chỉnh sửa bài viết')
@section('title_page', 'Chỉnh sửa bài viết')
@section('sub_title_page', 'Chỉnh sửa bài viết')

@section('content_page')
<script>
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            var forms = document.getElementsByClassName('needs-validation');
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>

<div class="card-body">
    <h5 class="card-title">Chỉnh sửa bài viết</h5>
    <form class="needs-validation" action="{{route('post.update', $post->id)}}" method="POST" enctype="multipart/form-data" novalidate>
        @csrf
        @method('PUT')
        <div class="form-row">
            <div class="col-md-6 mb-3">
                <label for="validationTooltip01">Sản phẩm</label>
                <select class="mb-2 form-control" name="product_id">
                    <option value="{{$post->product->id}}">{{$post->product->name}}</option>
                </select>
            </div>

            <div class="col-md-12 mb-3">
                <label for="validationTooltip01">Mô tả bài viết</label>
                <textarea style="resize: none" rows="3" class="form-control" name="title" id="ckeditor1" placeholder="Mô tả cho bài viết">{{$post->title}}</textarea>
            </div>

            <div class="col-md-12 mb-3">
                <label for="validationTooltip01">Nôi dung bài viết</label>
                <textarea style="resize: none" rows="10" class="form-control" name="content" id="ckeditor2" placeholder="Nội dung cho bài viết">{{$post->content}}</textarea>
            </div>

        </div>

        <div class="form-row text-center">
            <div class="col-md-12 mb-3 mt-2">
                <button class="btn btn-success " name="submit" style="padding-left: 35px; padding-right:35px ;" type="submit">Cập nhập</button>
            </div>
        </div>

    </form>
</div>
@endsection

code/resources/views/admin/post/list.blade.php
@extends('admin.layouts.master')
@section('title', 'Danh sách bài viết')
@section('title_page', 'Danh sách bài viết')
@section('sub_title_page', 'Danh sách bài viết')

@section('content_page')
<div class="card-header">Danh sách bài viết</div>
<div class="table-responsive" style="padding-bottom: 10px;">
    @if(count($posts))
    <table class="align-middle mb-0 table table-borderless table-striped table-hover">
        <thead>
            <tr>
                <th class="text-center">STT</th>
                <th>Tiêu đề</th>
                <th class="text-center">Mô tả</th>
                <th class="text-center">Nội dung</th>
                <th class="text-center">Tính năng</th>
            </tr>
        </thead>
        <tbody>
            <?php $i = 1; ?>
            @foreach($posts as $post)
            <tr>
                <td class="text-center text-muted">
                    <?php
                    echo $i;
                    $i++;
                    ?>
                </td>

                <td class="text-center text-muted">{{$post->product->name}}</td>
                <td class="text-center text-muted">{{ Str::limit($post->title, 50) }} </td>
                <td class="text-center text-muted">{{ Str::limit($post->content, 50) }}</td>
                <td class="text-center">
                    <a href="{{route('post.edit', $post->id)}}" class="btn btn-primary btn-sm">Chỉnh sửa</a>
                    <form action="{{route('post.destroy', $post->id)}}" class="form-delete" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger btn-sm">Xóa</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <div class="text-center text-noti">Không có bài viết nào để hiển thị</div>
    @endif
</div>
@endsection