code/routes/web.php
        Route::get('/', 'UserAuthController@signup')->name('user.signup_get');
        Route::post('/', 'UserAuthController@handle_signup')->name('user.signup_post');
    });
    Route::group(['prefix' => 'signin'], function () {
        Route::get('/', 'UserAuthController@signin')->name('user.signin_get');
        Route::post('/', 'UserAuthController@handle_signin')->name('user.signin_post');
        Route::get('google', 'SocialLoginController@redirect_to_google')->name('social.google');
        Route::get('zalo', 'SocialLoginController@redirect_to_zalo')->name('social.zalo');
        Route::get('facebook', 'SocialLoginController@redirect_to_facebook')->name('social.facebook');
        Route::get('zalo-social', 'SocialLoginController@handle_signin_zalo');
        Route::get('google-social', 'SocialLoginController@handle_signin_google');
        Route::get('facebook-social', 'SocialLoginController@handle_signin_facebook');
    });
    Route::get('forgot-password', 'UserController@forgot_password')->name('user.forgot_password');
    Route::get('new-password/{code}', 'UserController@new_password')->name('user.new_password');
    Route::post('set-password', 'UserController@set_password')->name('user.set_password');
    Route::post('send-mail-password', 'MailController@handle_mail_reset_password')->name('mail.reset_password');


    Route::group(['prefix' => 'notification'], function () {
        Route::post('save-token', 'NotificationController@save_token');
    });

    Route::group(['middleware' => ['auth_user']], function () {
        Route::group(['prefix' => 'user'], function () {
            Route::get('/', 'UserController@index')->name('user.index');
            Route::post('update', 'UserController@update')->name('user.update');
        });
        Route::get('signout', 'UserAuthController@signout')->name('user.signout');
        Route::group(['prefix' => 'comment'], function () {
            Route::post('update', 'CommentController@update')->name('comment.update');
            Route::post('store', 'CommentController@store')->name('comment.store');
            Route::post('delete', 'CommentController@delete')->name('comment.delete');
        });
        Route::group(['prefix' => 'cart'], function () {
            Route::post('delete', 'CartController@delete')->name('cart.delete');
            Route::post('update', 'CartController@update')->name('cart.update');
            Route::post('store', 'CartController@store')->name('cart.store');
        });
        Route::group(['prefix' => 'checkout'], function () {
            Route::get('/', 'CheckoutController@index')->name('checkout.index');
            Route::post('calc-feeship', 'CheckoutController@calc_feeship')->name('checkout.calc_feeship');
        });
        Route::group(['prefix' => 'order'], function () {
            Route::get('/', 'OrderController@index')->name('order.index');
            Route::get('detail/{id}', 'OrderController@show')->name('order.show');
            Route::get('delete/{id}', 'OrderController@delete')->name('order.delete');

            Route::get('payment_callback', 'OrderController@payment_callback')->name('payment.callback');
            Route::post('order-confirm', 'OrderController@confirm_order')->name('order.confirm');
            Route::get('print-order/{id}', 'OrderController@print_order')->name('order.print');
        });
        Route::post('use-coupon', 'CouponController@use_coupon')->name('coupon.use_coupon');
        Route::post('select-delivery', 'DeliveryController@select_delivery');
        Route::group(['prefix' => 'chat'], function () {
            Route::post('get', 'ChatController@get_user_chat');
            Route::post('send', 'ChatController@send_user_chat');
        });
    });
});

//print
Route::group(['prefix' => 'print'], function () {
    Route::get('order/{code}', 'OrderController@print_order_new'); //middleware admin
});

//admin route
Route::get('admin/signin', 'AdminAuthController@signin')->name('admin.signin');
Route::post('admin/signin', 'AdminAuthController@handle_signin')->name('admin.handle_signin');
Route::group(['prefix' => 'admin',  'middleware' => ['auth:admin', 'auth_admin']], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('signout', 'AdminAuthController@signout')->name('admin.signout');
    Route::post('send-coupon', 'MailController@send_coupon');
    Route::group(['middleware' => 'can:' . config('role.ROLE')], function () {
        Route::resource('role', 'RoleController');
    });
    Route::group(['middleware' => 'can:' . config('role.POST')], function () {
        Route::resource('post', 'PostController');
    });
    Route::group(['middleware' => 'can:' . config('role.STATISTIC')], function () {
        Route::get('static', 'StaticController@index')->name('static.index');
    });
    Route::group(['middleware' => 'can:' . config('role.SLIDER')], function () {
        Route::resource('slider', 'SliderController');
    });
    Route::group(['middleware' => 'can:' . config('role.INFO')], function () {
        Route::get('device', 'DeviceController@admin_device')->name('device.admin');
        Route::resource('visitor', 'VisitorController');
    });
    Route::group(['middleware' => 'can:' . config('role.ADMIN')], function () {
        Route::get('list', 'AdminController@list')->name('admin.list');
        Route::get('add', 'AdminController@add')->name('admin.add');
        Route::get('edit/{id}', 'AdminController@edit')->name('admin.edit');
        Route::post('update/{id}', 'AdminController@update')->name('admin.update');
        Route::post('store', 'AdminController@store')->name('admin.store');
        Route::get('delete/{id}', 'AdminController@destroy')->name('admin.delete');
    });
    Route::group(['middleware' => 'can:' . config('role.BRAND')], function () {
        Route::post('brand/sort', 'BrandController@sort');
        Route::resource('brand', 'BrandController');
    });
    Route::group(['middleware' => 'can:' . config('role.COUPON')], function () {
        Route::post('coupon/send', 'CouponController@send');
        Route::resource('coupon', 'CouponController');
    });
    Route::group(['middleware' => 'can:' . config('role.COMMENT')], function () {
        Route::group(['prefix' => 'comment'], function () {
            Route::get('/', 'CommentController@index')->name('comment.index');
            Route::get('not-confirm', 'CommentController@get_not_confirm')->name('comment.not_confirm');
            Route::get('confirm/{id}', 'CommentController@set_confirm')->name('comment.confirm');
            Route::post('delete', 'CommentController@delete')->name('comment.delete');
        });
    });
    Route::group(['middleware' => 'can:' . config('role.ORDER')], function () {
        Route::group(['prefix' => 'order'], function () {
            Route::get('/', 'OrderController@manage')->name('order.manage');
            Route::get('/{id}', 'OrderController@admin_detail')->name('order.admin_detail');
            Route::get('print-order/{id}', 'OrderController@print_order')->name('order.admin_print');
            Route::get('order-delete/{id}', 'OrderController@admin_delete')->name('order.admin_delete');
            Route::get('order-delivery/{id}', 'OrderController@delivery')->name('order.delivery');
        });
    });
    Route::group(['middleware' => 'can:' . config('role.FEESHIP')], function () {
        Route::group(['prefix' => 'delivery'], function () {
            Route::post('select', 'DeliveryController@select_delivery')->name('delivery.select');
            Route::get('/', 'DeliveryController@index')->name('delivery.index');
            Route::post('store', 'DeliveryController@store')->name('delivery.store');
            Route::post('show', 'DeliveryController@show')->name('delivery.show');
            Route::post('delete', 'DeliveryController@delete')->name('delivery.delete');
        });
    });
    Route::group(['middleware' => 'can:' . config('role.PRODUCT')], function () {
        Route::group(['prefix' => 'product'], function () {
            Route::get('reference', 'ProductController@reference')->name('product.reference');
            Route::get('gallery/{id}', 'ProductController@product_gallery')->name('product.gallery');
            Route::get('delete-gallery/{id}', 'ProductController@delete_gallery')->name('product.gallery.delete');
            Route::post('gallery-store/{id}', 'ProductController@product_gallery_store')->name('product.gallery.store');
            Route::post('get-product-crawl', 'ProductController@get_product_crawl')->name('product.get_product_crawl');
            Route::post('add-product-crawl', 'ProductController@add_product_crawl')->name('product.add_product_crawl');
        });
        Route::resource('product', 'ProductController');
    });
    Route::group(['middleware' => 'can:' . config('role.USER')], function () {
        Route::group(['prefix' => 'user'], function () {
            Route::get('/', 'UserController@all_user')->name('user.list');
            Route::get('more/{id}', 'UserController@more_feature')->name('user.more');
            Route::post('unblock', 'UserController@unblock')->name('user.unblock');
            Route::post('block', 'UserController@block')->name('user.block');
            Route::post('delete', 'UserController@delete')->name('user.delete');
            Route::match(['get', 'post'], 'online', 'UserController@online_user')->name('user.online');
        });
        Route::get('device/{id}', 'DeviceController@user_device')->name('device.user');
        Route::group(['prefix' => 'chat'], function () {
            Route::post('get', 'ChatController@get_admin_chat');
            Route::post('send', 'ChatController@send_admin_chat');
        });
    });

    Route::group(['prefix' => 'notification'], function () {
        Route::get('add', 'NotificationController@add')->name('noti.add');

code/app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    protected $fillable = [
        'name',
        'description',
    ];

    public function products()
    {
        return $this->hasMany('App\Models\Product', 'brand_id');
    }

    public static function sort($brand_ids)
    {
        foreach ($brand_ids as $key =>  $brand_id) {
            Brand::where('id', $brand_id)->update(['brand_order' =>  $key]);
        }
    }
}

code/app/Http/Controllers/Api/BrandController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\BrandService;
use Exception;

class BrandController extends Controller
{
    protected $brandService;

    public function __construct(BrandService $brandService)
    {
        $this->brandService = $brandService;
    }

    public function get_all_brand()
    {
        $brands = $this->brandService->getAllBrand();
        return $this->successResponse($brands);
    }

    public function update_brand(Request $req)
    {
        try {
            $this->brandService->updateOrSave($req);
            return $this->successResponse();
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }

    public function delete_brand(Request $req)
    {
        try {
            $this->brandService->delete($req);
            return $this->successResponse();
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }

    public function import_excel(Request $req)
    {
        try {
            $this->brandService->importExcel($req);
            return $this->successResponse();
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }

    public function export_excel()
    {
        return $this->brandService->exportExcel();
    }
}

code/app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\BrandRequest;
use App\Models\Brand;

class BrandController extends Controller
{
    public function index()
    {
        $brands = Brand::oldest('brand_order')->get();
        return view('admin.brand.list')->with(compact(['brands']));
    }

    public function create()
    {
        return view('admin.brand.add');
    }

    public function store(BrandRequest $req)
    {
        $brand = new Brand;
        $brand->fill($req->all());
        $brand->save();

        return redirect()->route('brand.index');
    }

    public function edit(Brand $brand)
    {
        return view('admin.brand.edit')->with(compact(['brand']));
    }

    public function update(BrandRequest $req, $id)
    {
        Brand::where('id', $id)->update($req->only('name', 'description'));
        return redirect()->route('brand.index');
    }

    public function sort(Request $req)
    {
        Brand::sort($req->page_id_array);
    }

    public function destroy($id)
    {
        Brand::destroy($id);
        return \redirect()->route('brand.index');
    }
}

code/resources/views/admin/brand/add.blade.php
@extends('admin.layouts.master')
@section('title', 'Thêm thương hiệu')
@section('title_page', 'Thêm thương hiệu')
@section('sub_title_page', 'Thêm thương hiệu sản phẩm')

@section('content_page')
<script>
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            var forms = document.getElementsByClassName('needs-validation');
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>

<div class="card-body">
    <h5 class="card-title">Thêm thương hiệu</h5>
    <form class="needs-validation" action="{{route('brand.store')}}" method="POST" enctype="multipart/form-data" novalidate>
        @csrf
        <div class="form-row">
            <div class="col-md-6 mb-3">
                <label for="validationTooltip01">Tên thương hiệu</label>
                <input type="text" class="form-control" id="validationTooltip01" name="name" placeholder="Tên thương hiệu" value="" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                @if ($errors->has('name'))
                <div class="">{{ $errors->first('name') }}</div>
                @endif
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-6 mb-3">
                <label for="validationTooltip01">Mô tả</label>
                <input type="text" class="form-control" id="validationTooltip01" name="description" placeholder="Mô tả" value="" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                @if ($errors->has('description'))
                <div class="">{{ $errors->first('description') }}</div>
                @endif
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>
        </div>

        <div class="form-row text-center">
            <div class="col-md-12 mb-3 mt-2">
                <button class="btn btn-success " name="submit" style="padding-left: 35px; padding-right:35px ;" type="submit">Thêm</button>
            </div>
        </div>

    </form>
</div>
@endsection

code/resources/views/admin/brand/edit.blade.php
@extends('admin.layouts.master')
@section('title', 'Chỉnh sửa thương hiệu')
@section('title_page', 'Chỉnh sủa thương hiệu')
@section('sub_title_page', 'Chỉnh sủa thương hiệu sản phẩm')

@section('content_page')
<script>
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            var forms = document.getElementsByClassName('needs-validation');
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>

<div class="card-body">
    <h5 class="card-title">Chỉnh sửa thương hiệu</h5>
    <form class="needs-validation" action="{{route('brand.update', $brand->id)}}" method="POST" enctype="multipart/form-data" novalidate>
        @csrf
        @method('PUT')
        <div class="form-row">
            <div class="col-md-6 mb-3">
                <label for="validationTooltip01">Tên thương hiệu</label>
                <input type="text" class="form-control" id="validationTooltip01" name="name" placeholder="Tên danh mục" value="{{$brand->name}}" required>
                <div class="invalid-feedback" style="font-size: 20px;">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-6 mb-3">
                <label for="validationTooltip01">Mô tả</label>
                <input type="text" class="form-control" id="validationTooltip01" name="description" placeholder="Mô tả" value="{{$brand->description}}" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>
        </div>

        <div class="form-row text-center">
            <div class="col-md-12 mb-3 mt-3">
                <button class="btn btn-success " style="padding-left: 35px; padding-right:35px ;" name="submit" type="submit">Cập nhập</button>
            </div>
        </div>
    </form>
</div>
@endsection

code/resources/views/admin/brand/list.blade.php
@extends('admin.layouts.master')
@section('title', 'Danh sách thương hiệu sản phẩm')
@section('title_page', 'Thương hiệu')
@section('sub_title_page', 'Danh sách thương hiệu')

@section('content_page')
<div class="card-header">Danh sách thương hiệu</div>
<div class="table-responsive" style="padding-bottom: 10px;">
    @if(count($brands) > 0)
    <table class="align-middle mb-0 table table-borderless table-striped table-hover">
        <thead>
            <tr>
                <th class="text-center">STT</th>
                <th>Tên thương hiệu</th>
                <th class="text-center">Tính năng</th>
            </tr>
        </thead>
        <tbody id="brand-list">
            <?php $i = 1; ?>
            @foreach ($brands as $brand)
            <tr id="{{$brand->id}}">
                <td class="text-center text-muted">
                    <?php
                    echo $i;
                    $i++;
                    ?>
                </td>
                <td>
                    <div class="widget-content p-0">
                        <div class="widget-content-wrapper">
                            <div class="widget-content-left mr-3">
                                <div class="widget-content-left">
                                </div>
                            </div>
                            <div class="widget-content-left flex2">
                                <div class="widget-heading">{{$brand->name}}</div>
                                <div class="widget-subheading opacity-7">{{$brand->description}}</div>
                            </div>
                        </div>
                    </div>
                </td>
                <td class="text-center">
                    <a href="{{route('brand.edit', $brand->id)}}" class="btn btn-primary btn-sm">Chỉnh sửa</a>
                    <form action="{{route('brand.destroy', $brand->id)}}" class="form-delete" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger btn-sm">Xóa</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <div class="text-center text-noti">Không có thương hiệu nào để hiển thị</div>
    @endif
</div>
@endsection