code/routes/web.php
        Route::get('/', 'UserAuthController@signup')->name('user.signup_get');
        Route::post('/', 'UserAuthController@handle_signup')->name('user.signup_post');
    });
    Route::group(['prefix' => 'signin'], function () {
        Route::get('/', 'UserAuthController@signin')->name('user.signin_get');
        Route::post('/', 'UserAuthController@handle_signin')->name('user.signin_post');
        Route::get('google', 'SocialLoginController@redirect_to_google')->name('social.google');
        Route::get('zalo', 'SocialLoginController@redirect_to_zalo')->name('social.zalo');
        Route::get('facebook', 'SocialLoginController@redirect_to_facebook')->name('social.facebook');
        Route::get('zalo-social', 'SocialLoginController@handle_signin_zalo');
        Route::get('google-social', 'SocialLoginController@handle_signin_google');
        Route::get('facebook-social', 'SocialLoginController@handle_signin_facebook');
    });
    Route::get('forgot-password', 'UserController@forgot_password')->name('user.forgot_password');
    Route::get('new-password/{code}', 'UserController@new_password')->name('user.new_password');
    Route::post('set-password', 'UserController@set_password')->name('user.set_password');
    Route::post('send-mail-password', 'MailController@handle_mail_reset_password')->name('mail.reset_password');


    Route::group(['prefix' => 'notification'], function () {
        Route::post('save-token', 'NotificationController@save_token');
    });

    Route::group(['middleware' => ['auth_user']], function () {
        Route::group(['prefix' => 'user'], function () {
            Route::get('/', 'UserController@index')->name('user.index');
            Route::post('update', 'UserController@update')->name('user.update');
        });
        Route::get('signout', 'UserAuthController@signout')->name('user.signout');
        Route::group(['prefix' => 'comment'], function () {
            Route::post('update', 'CommentController@update')->name('comment.update');
            Route::post('store', 'CommentController@store')->name('comment.store');
            Route::post('delete', 'CommentController@delete')->name('comment.delete');
        });
        Route::group(['prefix' => 'cart'], function () {
            Route::post('delete', 'CartController@delete')->name('cart.delete');
            Route::post('update', 'CartController@update')->name('cart.update');
            Route::post('store', 'CartController@store')->name('cart.store');
        });
        Route::group(['prefix' => 'checkout'], function () {
            Route::get('/', 'CheckoutController@index')->name('checkout.index');
            Route::post('calc-feeship', 'CheckoutController@calc_feeship')->name('checkout.calc_feeship');
        });
        Route::group(['prefix' => 'order'], function () {
            Route::get('/', 'OrderController@index')->name('order.index');
            Route::get('detail/{id}', 'OrderController@show')->name('order.show');
            Route::get('delete/{id}', 'OrderController@delete')->name('order.delete');

            Route::get('payment_callback', 'OrderController@payment_callback')->name('payment.callback');
            Route::post('order-confirm', 'OrderController@confirm_order')->name('order.confirm');
            Route::get('print-order/{id}', 'OrderController@print_order')->name('order.print');
        });
        Route::post('use-coupon', 'CouponController@use_coupon')->name('coupon.use_coupon');
        Route::post('select-delivery', 'DeliveryController@select_delivery');
        Route::group(['prefix' => 'chat'], function () {
            Route::post('get', 'ChatController@get_user_chat');
            Route::post('send', 'ChatController@send_user_chat');
        });
    });
});

//print
Route::group(['prefix' => 'print'], function () {
    Route::get('order/{code}', 'OrderController@print_order_new'); //middleware admin
});

//admin route
Route::get('admin/signin', 'AdminAuthController@signin')->name('admin.signin');
Route::post('admin/signin', 'AdminAuthController@handle_signin')->name('admin.handle_signin');
Route::group(['prefix' => 'admin',  'middleware' => ['auth:admin', 'auth_admin']], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('signout', 'AdminAuthController@signout')->name('admin.signout');
    Route::post('send-coupon', 'MailController@send_coupon');
    Route::group(['middleware' => 'can:' . config('role.ROLE')], function () {
        Route::resource('role', 'RoleController');
    });
    Route::group(['middleware' => 'can:' . config('role.POST')], function () {
        Route::resource('post', 'PostController');
    });
    Route::group(['middleware' => 'can:' . config('role.STATISTIC')], function () {
        Route::get('static', 'StaticController@index')->name('static.index');
    });
    Route::group(['middleware' => 'can:' . config('role.SLIDER')], function () {
        Route::resource('slider', 'SliderController');
    });
    Route::group(['middleware' => 'can:' . config('role.INFO')], function () {
        Route::get('device', 'DeviceController@admin_device')->name('device.admin');
        Route::resource('visitor', 'VisitorController');
    });
    Route::group(['middleware' => 'can:' . config('role.ADMIN')], function () {
        Route::get('list', 'AdminController@list')->name('admin.list');
        Route::get('add', 'AdminController@add')->name('admin.add');
        Route::get('edit/{id}', 'AdminController@edit')->name('admin.edit');
        Route::post('update/{id}', 'AdminController@update')->name('admin.update');
        Route::post('store', 'AdminController@store')->name('admin.store');
        Route::get('delete/{id}', 'AdminController@destroy')->name('admin.delete');
    });
    Route::group(['middleware' => 'can:' . config('role.BRAND')], function () {
        Route::post('brand/sort', 'BrandController@sort');
        Route::resource('brand', 'BrandController');
    });
    Route::group(['middleware' => 'can:' . config('role.COUPON')], function () {
        Route::post('coupon/send', 'CouponController@send');
        Route::resource('coupon', 'CouponController');
    });
    Route::group(['middleware' => 'can:' . config('role.COMMENT')], function () {
        Route::group(['prefix' => 'comment'], function () {
            Route::get('/', 'CommentController@index')->name('comment.index');
            Route::get('not-confirm', 'CommentController@get_not_confirm')->name('comment.not_confirm');
            Route::get('confirm/{id}', 'CommentController@set_confirm')->name('comment.confirm');
            Route::post('delete', 'CommentController@delete')->name('comment.delete');
        });
    });
    Route::group(['middleware' => 'can:' . config('role.ORDER')], function () {
        Route::group(['prefix' => 'order'], function () {
            Route::get('/', 'OrderController@manage')->name('order.manage');
            Route::get('/{id}', 'OrderController@admin_detail')->name('order.admin_detail');
            Route::get('print-order/{id}', 'OrderController@print_order')->name('order.admin_print');
            Route::get('order-delete/{id}', 'OrderController@admin_delete')->name('order.admin_delete');
            Route::get('order-delivery/{id}', 'OrderController@delivery')->name('order.delivery');
        });
    });
    Route::group(['middleware' => 'can:' . config('role.FEESHIP')], function () {
        Route::group(['prefix' => 'delivery'], function () {
            Route::post('select', 'DeliveryController@select_delivery')->name('delivery.select');
            Route::get('/', 'DeliveryController@index')->name('delivery.index');
            Route::post('store', 'DeliveryController@store')->name('delivery.store');
            Route::post('show', 'DeliveryController@show')->name('delivery.show');
            Route::post('delete', 'DeliveryController@delete')->name('delivery.delete');
        });
    });
    Route::group(['middleware' => 'can:' . config('role.PRODUCT')], function () {
        Route::group(['prefix' => 'product'], function () {
            Route::get('reference', 'ProductController@reference')->name('product.reference');
            Route::get('gallery/{id}', 'ProductController@product_gallery')->name('product.gallery');
            Route::get('delete-gallery/{id}', 'ProductController@delete_gallery')->name('product.gallery.delete');
            Route::post('gallery-store/{id}', 'ProductController@product_gallery_store')->name('product.gallery.store');
            Route::post('get-product-crawl', 'ProductController@get_product_crawl')->name('product.get_product_crawl');
            Route::post('add-product-crawl', 'ProductController@add_product_crawl')->name('product.add_product_crawl');
        });
        Route::resource('product', 'ProductController');
    });
    Route::group(['middleware' => 'can:' . config('role.USER')], function () {
        Route::group(['prefix' => 'user'], function () {
            Route::get('/', 'UserController@all_user')->name('user.list');
            Route::get('more/{id}', 'UserController@more_feature')->name('user.more');
            Route::post('unblock', 'UserController@unblock')->name('user.unblock');
            Route::post('block', 'UserController@block')->name('user.block');
            Route::post('delete', 'UserController@delete')->name('user.delete');
            Route::match(['get', 'post'], 'online', 'UserController@online_user')->name('user.online');
        });
        Route::get('device/{id}', 'DeviceController@user_device')->name('device.user');
        Route::group(['prefix' => 'chat'], function () {
            Route::post('get', 'ChatController@get_admin_chat');
            Route::post('send', 'ChatController@send_admin_chat');
        });
    });

    Route::group(['prefix' => 'notification'], function () {
        Route::get('add', 'NotificationController@add')->name('noti.add');

code/app/Models/Coupon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    protected $fillable = [
        'name',
        'code',
        'quantity',
        'money',
        'start_coupon',
        'end_coupon',
        'status',
    ];
}

code/app/Http/Controllers/Api/CouponController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\CouponService;
use Exception;

class CouponController extends Controller
{
    protected $couponService;

    public function __construct(CouponService $couponService)
    {
        $this->couponService = $couponService;
    }

    public function use_coupon(Request $req)
    {
        try {
            $result = $this->couponService->useCoupon($req);
            return $this->successResponse($result);
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }

    public function all_coupon()
    {
        $coupons = $this->couponService->getAll();
        return $this->successResponse($coupons);
    }

    public function delete_coupon(Request $req)
    {
        try {
            $this->couponService->delete($req);
            return $this->successResponse();
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }

    public function update_coupon(Request $req)
    {
        try {
            $this->couponService->update($req);
            return $this->successResponse();
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }

    public function new_coupon(Request $req)
    {
        try {
            $this->couponService->save($req);
            return $this->successResponse();
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }

    public function send_coupon(Request $req)
    {
        try {
            $result = $this->couponService->sendCoupon($req);
            return $this->successResponse($result);
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }

    public function import_excel(Request $req)
    {
        try {
            $this->couponService->importExcel($req);
            return $this->successResponse();
        } catch (Exception $e) {
            return $this->errorResponse($e->getMessage());
        }
    }

    public function export_excel()
    {
        return $this->couponService->exportExcel();
    }
}

code/app/Http/Controllers/CouponController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CouponRequest;
use Illuminate\Support\Facades\Auth;
use App\Models\Coupon;
use App\Models\User;
use Carbon\Carbon;

class CouponController extends Controller
{
    public function index()
    {
        $coupons = Coupon::all();
        $users = User::all();
        $today = Carbon::now('Asia/Ho_Chi_Minh')->format('d/m/Y');
        return view('admin.coupon.list')->with(compact(['coupons', 'today', 'users']));
    }

    public function create()
    {
        return view('admin.coupon.add');
    }

    public function edit(Coupon $coupon)
    {
        return view('admin.coupon.edit')->with(compact(['coupon']));
    }

    public function update(CouponRequest $req, $id)
    {
        $coupon = Coupon::find($id);
        $coupon->fill($req->all());
        $coupon->save();
        return redirect()->route('coupon.index');
    }

    public function store(CouponRequest $req)
    {
        $coupon = new Coupon;
        $coupon->fill($req->all());
        $coupon->save();
        return redirect()->route('coupon.index');
    }

    public function destroy($id)
    {
        Coupon::destroy($id);
        return \redirect()->route('coupon.index');
    }

    private function has_used($coupon)
    {
        $useds =  explode(",", $coupon->used);
        return in_array(Auth::user()->id, $useds);
    }

    public function use_coupon(Request $req)
    {
        session()->forget(['coupon', 'message', 'error']);

        $today = Carbon::now('Asia/Ho_Chi_Minh')->format('Y-m-d');
        $coupon = Coupon::where([
            ['code', '=', $req->code],
            ['end_coupon', '>=', $today]
        ])->first();

        if (!$coupon) {
            session(['error' => 'Mã giảm giá không đúng hoặc đã hết hạn']);
        } else {
            if ($this->has_used($coupon)) {
                session(['error' => 'Bạn đã sử dụng mã giảm giá này rồi']);
            } else {
                $new_oupon = [
                    'code' => $coupon->code,
                    'money' => $coupon->money,
                ];
                session(['coupon' =>  $new_oupon]);
                session(['message' => 'Thêm mã giảm giá thành công']);
            }
        }
    }
}

code/resources/views/admin/coupon/add.blade.php
@extends('admin.layouts.master')
@section('title', 'Thêm mã giảm giá')
@section('title_page', 'Thêm mã giảm giá')
@section('sub_title_page', 'Thêm mã giảm giá cho sản phẩm')

@section('content_page')
<script>
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            var forms = document.getElementsByClassName('needs-validation');
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>

<div class="card-body">
    <h5 class="card-title">Thêm mã giảm giá</h5>
    <form class="needs-validation" action="{{route('coupon.store')}}" method="POST" enctype="multipart/form-data" novalidate>
        @csrf
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Tên mã giảm giá</label>
                <input type="text" class="form-control" name="name" id="validationTooltip01" placeholder="Tên mã giảm giá" value="" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Mã mã giảm giá</label>
                <input type="text" class="form-control" name="code" id="validationTooltip01" placeholder="Mã mã giảm giá" value="" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Số lượng mã giảm giá</label>
                <input type="text" class="form-control" name="quantity" id="validationTooltip01" placeholder="Số lượng mã giảm giá" value="" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Số tiền giảm</label>
                <input type="number" class="form-control" name="money" id="validationTooltip01" placeholder="Số tiền giảm giá" min="1" max="100" value="" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Ngày băt đầu</label>
                <input type="text" class="form-control" name="start_coupon" id="start_coupon" placeholder="Ngày băt đầu" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Ngày kết thúc</label>
                <input type="text" class="form-control" name="end_coupon" id="end_coupon" placeholder="Ngày kết thúc" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>
        </div>
        @if ($errors->any())
        @foreach ($errors->all() as $error)
        {{ $error }}
        @endforeach
        @endif
        <div class="form-row text-center">
            <div class="col-md-12 mb-3 mt-2">
                <button class="btn btn-success " name="submit" style="padding-left: 35px; padding-right:35px ;" type="submit">Thêm</button>
            </div>
        </div>


    </form>
</div>
@endsection

code/resources/views/admin/coupon/edit.blade.php
@extends('admin.layouts.master')
@section('title', 'Chỉnh sửa mã giảm giá')
@section('title_page', 'Chỉnh sửa mã giảm giá')
@section('sub_title_page', 'Chỉnh sửa mã giảm giá')

@section('content_page')
<script>
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            var forms = document.getElementsByClassName('needs-validation');
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>

<div class="card-body">
    <h5 class="card-title">Chỉnh sửa mã giảm giá</h5>
    <form class="needs-validation" action="{{route('coupon.update', $coupon->id)}}" method="POST" enctype="multipart/form-data" novalidate>
        @csrf
        @method('PUT')
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Tên mã giảm giá</label>
                <input type="text" class="form-control" name="name" id="validationTooltip01" placeholder="Tên mã giảm giá" value="{{$coupon->name}}" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Mã mã giảm giá</label>
                <input type="text" class="form-control" name="code" id="validationTooltip01" placeholder="Mã mã giảm giá" value="{{$coupon->code}}" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Số lượng mã giảm giá</label>
                <input type="text" class="form-control" name="quantity" id="validationTooltip01" placeholder="Số lượng mã giảm giá" value="{{$coupon->quantity}}" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Số tiền giảm giá</label>
                <input type="number" class="form-control" name="money" id="validationTooltip01" placeholder="Phần trăm giảm giá" min="1" max="100" value="{{$coupon->money}}" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Ngày băt đầu</label>
                <input type="text" class="form-control" name="start_coupon" id="start_coupon" value="{{$coupon->start_coupon}}" placeholder="Ngày băt đầu" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>

            <div class="col-md-4 mb-3">
                <label for="validationTooltip01">Ngày kết thúc</label>
                <input type="text" class="form-control" name="end_coupon" id="end_coupon" value="{{$coupon->end_coupon}}" placeholder="Ngày kết thúc" required>
                <div class="invalid-feedback">Vui lòng nhập đầy đủ dữ liệu.</div>
                <div class="valid-feedback">Tuyệt vời!!!</div>
            </div>
        </div>

        <div class="form-row text-center">
            <div class="col-md-12 mb-3 mt-2">
                <button class="btn btn-success" name="submit" style="padding-left: 35px; padding-right:35px ;" type="submit">Cập nhật</button>
            </div>
        </div>

    </form>
</div>
@endsection

code/resources/views/admin/coupon/list.blade.php
@extends('admin.layouts.master')
@section('title', 'Danh sách mã giảm giá')
@section('title_page', 'Danh sách mã giảm giá')
@section('sub_title_page', 'Danh sách mã giảm giá')

<div class="modal fade" id="modal-coupon" style="display: none;" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content model-send-coupon" role="document">
            <div class="card-header d-flex justify-content-between align-items-center">Danh sách người dùng <div data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i></div>
            </div>
            <div class="table-responsive" style="padding-bottom: 10px;">
                @if(count($users))
                <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">STT</th>
                            <th class="text-center">Tên khách hàng</th>
                            <th class="text-center">Email</th>
                            <th class="text-center">Tính năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $i = 1; @endphp
                        @foreach($users as $user)
                        <tr>
                            <td class="text-center text-muted">
                                <?php echo $i;
                                $i++;
                                ?>
                            </td>
                            <td>
                                <div class="widget-content p-0">
                                    <div class="widget-content-wrapper">
                                        <div class="widget-content-left mr-3">
                                            <div class="widget-content-left <?php if ($user->isOnline()) {
                                                                                echo "user-on";
                                                                            } ?>" style="position: relative;">
                                                <img class="rounded-circle border-circle" src="{{asset('admins/uploads/avatars/'.$user->image)}}" alt="">
                                            </div>
                                        </div>
                                        <div class="widget-content-left flex2">
                                            <div class="widget-heading">{{$user->name}}</div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td class="text-center text-muted">{{$user->email}}</td>

                            <td class="text-center">
                                <button data-id="{{$user->id}}" class="btn btn-success btn-sm send-to-user">Gửi mã</button>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                @else
                <div class="text-center text-noti">Không có người dùng nào để hiển thị</div>
                @endif
            </div>
        </div>
    </div>
</div>

@section('content_page')

<div class="card-header">Danh sách mã giảm giá</div>
<div class="table-responsive" style="padding-bottom: 10px;">
    @if(count($coupons) > 0)
    <table class="align-middle mb-0 table table-borderless table-striped table-hover">
        <thead>
            <tr>
                <th class="text-center">STT</th>
                <th>Tên mã giảm giá</th>
                <th class="text-center">Mã mã giảm giá</th>
                <th class="text-center">Số lượng</th>
                <th class="text-center">Phần trăm giảm giá</th>
                <th class="text-center">Ngày bắt đầu</th>
                <th class="text-center">Ngày kết thúc</th>
                <th class="text-center">Trạng thái</th>
                <th class="text-center">Tính năng</th>
            </tr>
        </thead>
        <tbody>
            <?php $i = 1; ?>
            @foreach ($coupons as $coupon)
            <tr>
                <td class="text-center text-muted">
                    <?php
                    echo $i;
                    $i++;
                    ?></td>
                <td class="text-center text-muted">{{$coupon->name}}</td>
                <td class="text-center text-muted">{{$coupon->code}}</td>
                <td class="text-center text-muted">{{$coupon->quantity}} Mã</td>
                <td class="text-center text-muted">{{$coupon->money}}%</td>
                <td class="text-center text-muted">{{$coupon->start_coupon}}</td>
                <td class="text-center text-muted">{{$coupon->end_coupon}}</td>
                <td class="text-center text-muted">
                    @if($coupon->end_coupon >= $today)
                    Còn hạn
                    @else
                    Hết hạn
                    @endif
                </td>
                <td class="text-center">
                    <button data-toggle="modal" data-target="#modal-coupon" data-id="{{$coupon->code}}" class="btn btn-success btn-sm send-coupon">Gửi mã</button>
                    <a href="{{route('coupon.edit', $coupon->id)}}" class="btn btn-primary btn-sm">Chỉnh sửa</a>
                    <form action="{{route('coupon.destroy', $coupon->id)}}" class="form-delete" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger btn-sm">Xóa</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <div class="text-center text-noti">Không có mã giảm giá nào để hiển thị</div>
    @endif
</div>
@endsection